seed_everything: 42

trainer:
  accelerator: auto
  devices: 1
  max_epochs: 1000
  
  # PyTorch Lightning parameter to force exactly 1 batch over and over
  overfit_batches: 1
  
  # Disable validation during overfitting
  limit_val_batches: 0
  num_sanity_val_steps: 0
  
  log_every_n_steps: 1
  enable_checkpointing: false
  
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        name: overfit-tex-gen
        project: tex-gen
        save_dir: .
        offline: false

  callbacks:
    # Diffusion Visualisation that now also logs to WandB
    - class_path: tex_gen.callbacks.DiffusionVisualisationCallback
      init_args:
        seq_len_range: [40, 150]
        every_n_epochs: 50 
        image_count: 4
        show_steps: [499, 300, 150, 0]
        show_forward: true
        
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
        
    - class_path: lightning.pytorch.callbacks.RichProgressBar
      init_args:
        refresh_rate: 1
        leave: false

model:
  lr: 0.001
  backbone:
    class_path: tex_gen.models.architectures.dit.DiT
    init_args:
        in_channels: 4       
        hidden_dim: 512      
        depth: 6             
        num_heads: 8         
        max_seq_len: 250     
  noise_scheduler:
    class_path: diffusers.DDPMScheduler
    init_args:
      num_train_timesteps: 500

data:
  data_dir: "data/mathwriting-2024/symbols" 
  batch_size: 8 
  num_workers: 1
  val_split: 0.1
